name: admin
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  adaptive_theme: ^3.0.0
  cupertino_icons: ^1.0.4
  easy_container: ^1.0.4+1
  elegant_notification: null
  fl_chart: ^0.50.6
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.5
  google_fonts: ^3.0.0
  pluto_grid: null
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0
  dotted_border: ^2.0.0+3
  group_radio_button: ^1.3.0

dev_dependencies: null

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 700

